version: 2.1

orbs:
  node: circleci/node@4.5.0

jobs:
  test:
    docker:
      - image: cypress/included:7.4.0
    steps:
      - checkout
      - node/install-packages
      - run: npm run build
      - run: npm run lint
      - run: npm run check-types
      - run: npm run test
      - run: npx cypress run --config-file cypress/configs/ci.json
      - store_artifacts:
          path: ./cypress/videos
          when: on_fail

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
